### ISSUE TITLE
OAuth Issue

### ISSUE THREAD

**Issue by hrangel** [neroniaky/angular2-token#119]
Hi,

Trying to setup my first project using angular2-token and oauth, I've reached to a strange dead-end.
Whenever I try to login (with google for instance) I get this URL built (at the method _buildOAuthUrl)
`${window.location.origin}/${oAuthPath}?omniauth_window_type=${windowType}&auth_origin_url=${encodeURIComponent(callbackUrl)}`

When the window.open method fires it shows:
`Cannot GET /$%7Bwindow.location.origin%7D/$%7BoAuthPath%7D?omniauth_window_type=${windowType}&auth_origin_url=${encodeURIComponent(callbackUrl)}`

It feels like a stupid tweak would solve everything, but I can't seem to find it.
Can you help?

I'm using version angular2-token 0.2.0-beta.6
My API runs at: http://localhost:3000/api/v1
My Angular2 runas at: http://localhost:8000

Here is my setup:
```
this._tokenService.init({
            apiPath: "http://localhost:3000/api/v1",
            oAuthPaths: {
                facebook: '/auth/facebook',
                google:   '/auth/google'
            }
        });
```

**Comment by neroniaky** [comment]
Hey @hrangel, OAuth currently does not work out of the box with rails api-only due to some problems with devise token auth. We are waiting for them to merge the PR [here](https://github.com/lynndylanhurley/devise_token_auth/pull/765). You can find further information [here](https://github.com/neroniaky/angular2-token-example/issues/4).

**Comment by hrangel** [comment]
Hey @neroniaky thanks for the answer!
That doesn't makes sense, at least in my head, the built address is completely wrong, that doesn't seem to bem rails fault. It doesn't seem like this URL went through rails api. It seems an angular String error.

**Comment by hrangel** [comment]
Another thing to notice that, if you try to log in on the Angular2-Token demo app, you can't:
https://angular2-token.herokuapp.com/#/
