### ISSUE TITLE
How to restrict user to sign-in again after successfull sign-in

### ISSUE THREAD

**Issue by jomarbarnobal** [neroniaky/angular2-token#120]
Hi Just want to ask 
How can i restrict user to sign-in again if the user is successfully signed-in?

For instance i signed-in and it was successful and redirect to home-page but if i navigate to sign-in url i can singed-in again.

Im new in angular2 and im using Rails5 for API
Thanks in advance

**Comment by neroniaky** [comment]
Hey @jomarbarnobal, if you sign in again (with another account) it'll change accounts, which sometimes can be helpful. If you want to block this behavior, you could roll your own CanActivate route guard, which uses the userSignedIn() method.

```
userSignedIn(): boolean {
      return !!this._currentAuthData;
}
```

**Comment by jomarbarnobal** [comment]
Thanks sir @neroniaky  it helps me a lot

One more question, how can i resolve this error ?
http://localhost:4200/auth/validate_token Failed to load resource: the server, i always get this error 

in my component ts 
`export class SignInComponent {

    private _errors: string[];

    constructor(
        private _formService: FormService,
        private _tokenService: Angular2TokenService,
        ){
        this._formService.initForm(SIGN_IN_FORM)
        this._tokenService.init({
            apiPath: 'https://blog-api-app.herokuapp.com'
        })

        this._formService.submit$.subscribe(
            (data: SignInData) => this._tokenService.signIn(data).subscribe(
                (res: any) => console.log(res),
                (error: any) => console.log(error)
            )
        )
    }
}`

**Comment by neroniaky** [comment]
Seems like the apiPath option does work as intended. I've to take a look into it.

**Comment by jomarbarnobal** [comment]
is there a way to bind currentUserData.id in hidden input field ? 
like this :   
`<input type="hidden" name="user_id" value="{{ _tokenService.currentUserData?.id}}"          [(ngModel)]="_postData.user_id">`  

coz i want to submit form with the id of ther user\
thanks in advance

**Comment by jomarbarnobal** [comment]
Question
how can i reference user in my submit form ?
i have this in my component
`
submitPost(form: NgModel){
   this.submitPost.post(this.value).subscribe(
     res => console.log(res),
     error => console.log(error)
   )
}
`
i want include the currentUserData.id
thanks in advance

**Comment by neroniaky** [comment]
Usually you don't get your user id from submitting with your data, because it would be a security risk. You can use the `current_user` variable in your rails controller instead. Hope this helps.

**Comment by jomarbarnobal** [comment]
so i have to us the userSignin() method in  component and pass to put ?

**Comment by jomarbarnobal** [comment]
I make it work now thanks @neroniaky, Sometimes reading documentation is helpful

here's what i did 

```
// In my post component_ts
submitPost(form: NgForm){
   this._tokenService.post(`v1/posts`, this._postData).subscribe(
   res => console.log(res),
   error => console.log(error)
  )
}
```

```
#in my rails api post_controller
def create
  post = current_user.posts.new(post_params)
    if post.save
  render json: post, status: :created 
  else
    render json: post.errors, status: :unprocessable_entity
  end
end
```
