### ISSUE TITLE
currentUserData return data if put some query to url

### ISSUE THREAD

**Issue by Kris-Simpson** [neroniaky/angular2-token#122]
If put this (for example) query: 
```
?client_id=random_id&config=default&expiry=1485717125&reset_password=true&token=random_token&uid=some%40email.com
```
 to any url, property `currentUserData` and method `userSignedIn()` will be returned positively, but user not logged in.

Is it a bug, or I miss something?

This "bug" appears on password resetting, when go to the url from email.

**Comment by neroniaky** [comment]
Hey @Kris-Simpson, the library doesn't check with the Backend on `.userSignedIn()`, which would be too slow in most cases, so it validates the format of the auth data only. 

If you want to make sure that the token is valid you can use `.validateToken()`.

**Comment by Kris-Simpson** [comment]
@neroniaky I mean, when user not logged in, and you put those params into url, the property `currentUserData` and method `userSignedIn()` will behave like when user logged in.

**Comment by neroniaky** [comment]
@Kris-Simpson yes that is correct, for the reasons I listed.

If you are concerned about security: Every request to the backend will fail, because you are not using a valid token.

**Comment by Kris-Simpson** [comment]
@neroniaky thank you, I think I understand you :)
