### ISSUE TITLE
npm install to build

### ISSUE THREAD

**Issue by hrangel** [neroniaky/angular2-token#123]
Hi everyone,

I'm using angular2-token (master branch) on my development environment and everything works fine after I've compiled "manually" the ts files. 

Sorry if that is a "noob" question, but is there any way to setup npm install to do that? Or should it be already doing that?

Regards,

Henrique

**Comment by neroniaky** [comment]
The npm package contains the build files only. If you want to bundle it yourself you could 1) clone the repo and use the service with webpack as part of your project or 2) run `npm run build`, which will give you the same result as the npm package.

**Comment by hrangel** [comment]
Thanks a lot @neroniaky I was about to clone the repo, but since you merged the changes I need it won't be need anymore!
But thanks anyway, it always good to learn something new.
