### ISSUE TITLE
AoT Fails because it cannot find BaseField

### ISSUE THREAD

**Issue by jburich** [neroniaky/angular2-token#126]
When I compile my code with the Angular 2 AoT compiler the code will compile successfully, however I run time I will get an error that says "Cannot find BaseField of undefined". 

I've done some digging around in the source and the problem is in lib/a2t-ui/a2t-shared/a2t-form/a2t-form-field.component.js the BaseField is imported as such:

`var _1 = require("../../../");`

If I change it to 

`var _1 = require("../../../a2t-ui.forms");` then everything works fine.

Obviously I don't want to go mucking around with a .js file inside my node_modules so I can put together a pull request this morning to update it, however I wanted to make sure that was a reasonable change to make in the code before I do.

I think as long as I'm at it I would make the same change in lib/a2t-ui/a2t-shared/a2t-form/a2t-form.service.d.ts. It is not causing me a problem at the moment, but I have a feeling that it would at some point since the code does the import the same way.

**Comment by neroniaky** [comment]
Hey @jburich thanks for you detailed description. The .js and .dt.s files are build from the .ts-files, so changes will be overwritten.
So we need to to change the a2t-form/a2t-form-field.component.ts to fix this error.

**Comment by jburich** [comment]
ah yes great point. I'll make the changes in the appropriate .ts files. thanks.

**Comment by jburich** [comment]
I see that you merged in the PR, did this get pushed to NPM yet?

**Comment by neroniaky** [comment]
Not yet.

**Comment by jburich** [comment]
do you have an eta on when that might be? I can use my forked repo for now if you think it'll be a while, but didn't want to switch over if you think it'll be soon. Not a problem either way, just want to do what's best.

**Comment by neroniaky** [comment]
I hope I can get this done this weekend.

**Comment by jburich** [comment]
awesome. thanks.
