### ISSUE TITLE
redirect_url for ResetPasswordData

### ISSUE THREAD

**Issue by artem-galas** [neroniaky/angular2-token#127]
Hi, I have noticed that there is no redirect_url for ResetPasswordData although it is one of the options for devise_token_auth - https://github.com/lynndylanhurley/devise_token_auth#usage-tldr

**Comment by neroniaky** [comment]
Hey @artem-galas the configuration parameter ist called `resetPasswordCallback`.

**Comment by artem-galas** [comment]
oh .. I'm sorry. Tired
