### ISSUE TITLE
Error with Ionic

### ISSUE THREAD

**Issue by dtelaroli** [neroniaky/angular2-token#129]
Error in :0:0 caused by: No provider for ActivatedRoute!

Maybe it's version conflict.

Ionic dependencies:
```
"@angular/common": "2.2.1",
    "@angular/compiler": "2.2.1",
    "@angular/compiler-cli": "2.2.1",
    "@angular/core": "2.2.1",
    "@angular/forms": "2.2.1",
    "@angular/http": "2.2.1",
    "@angular/platform-browser": "2.2.1",
    "@angular/platform-browser-dynamic": "2.2.1",
    "@angular/platform-server": "2.2.1",
    "@angular/router": "3.0.0",
    "@ionic/storage": "1.1.7",
    "ionic-angular": "2.0.0-rc.5",
    "ionic-native": "2.2.11",
    "ionicons": "3.0.0",
    "rxjs": "5.0.0-beta.12",
    "zone.js": "0.6.26",
    "sw-toolbox": "3.4.0",
    "angular2-token": "0.2.0-beta.7"
```

**Comment by neroniaky** [comment]
@dtelaroli I guess the dependencies should be fine, but I haven't tried myself.

**Comment by dtelaroli** [comment]
I created a [repository](https://github.com/dtelaroli/angular2-token) with Ionic and angular2-token to test with that problem.
I'm newbie with Angular2, so can be my mistake.

**Comment by neroniaky** [comment]
@dtelaroli I don't know enough about Iconic to do any debugging. 
`No provider for ActivatedRoute!` is a problem that shows up if you don't import `RouterModule` into your Root / AppModule. I don't know how Iconic handles this.

**Comment by neroniaky** [comment]
@dtelaroli I did some testing with ionic. Turn out it doesn't use the angular router, but their own version. Changing this seems to be not that easy.

I will check to build a version angular2-token, which doesn't depend on the router, but for now it doesn't work with ionic.

**Comment by dtelaroli** [comment]
@neroniaky Now it's possible try...
I got work fine the service configuration.
Thanks.

**Comment by jmargolese** [comment]
This still does not load with Ionic 3.
@version 0.2.0-beta.12

Does anyone have a working solution for Ionic 3?
(This version still tries to load from @angular/router which doesn't exist.)

thx


  `  typescript: node_modules/angular2-token/lib/angular2-token.service.d.ts, line: 1
            Cannot find module '@angular/router'.
       L1:  import { ActivatedRoute, Router, CanActivate } from '@angular/router';`

**Comment by hrangel** [comment]
Just made a PR with the updated version of angular-token: #488
