### ISSUE TITLE
Is ti possible to guard routes for specific user type

### ISSUE THREAD

**Issue by geoandri** [neroniaky/angular2-token#130]
Hi and congrats on your very helpful work.
I am in a position where I have two user types and I want to allow access to a group of  routes only for one userType users. Is this possible? I cannot find a way to "pass" this kind of information (userType) inside the Angular2TokenService. Routes guarded by the service are accessible for both userTypes. Is there any work around this? Are you planning on implementing this feature?

Thank you in advance

**Comment by neroniaky** [comment]
Hey @geoandri, thanks!
Angular2-Token implements the CanActivate interface for the most basic case. If you want a more complex route guard you can implement your own. `userSignedIn()` gives you the information if the user is signed in, `currentUserType()` the type of user that is signed in.
Hope this helps.

**Comment by geoandri** [comment]
Hi @neroniaky , thank you for your response. 
I ended up "cloning" angular2-token service and created two different services, one for each userType. 
Thanks again for your help
