### ISSUE TITLE
Using FormData with http methods 

### ISSUE THREAD

**Issue by olpdev7** [neroniaky/angular2-token#136]
Hi!
Is it possible to send formData with put, post, etc methods?
When I have something like:
```ts
@Component({})
export class Foo {
  public myForm: FormGroup;

  constructor(private angular2TokenService: Angular2TokenService) {}

  bar() {
    let someFormData = new FormData();
      Object.keys(this.myForm.value).forEach(k => {
      someFormData.append(k, this.myForm.value[k]);
    });
    this.angular2TokenService.put('url', someFormData).subscribe(res => {
      console.log(res);
    });
  }
}
```

I haven't someFormData in my request.
I finded workaround for myself by using:
``http.put`` with all needed headers instead: ``tokenService.put ``

I do something like:

```ts
@Component({})
export class Foo {
  public myForm: FormGroup;

  constructor(private http: Http) {
    this.headers = new Headers({
      'accessToken': localStorage.getItem('accessToken'),
      'client':       localStorage.getItem('client'),
      'expiry':       localStorage.getItem('expiry'),
      'tokenType':   localStorage.getItem('tokenType'),
      'uid':          localStorage.getItem('uid')
    });
  }

  bar() {
    let someFormData = new FormData();
      Object.keys(this.myForm.value).forEach(k => {
      someFormData.append(k, this.myForm.value[k]);
    });
    this.http.put('url', someFormData, {headers: this.headers}).subscribe(res => {
      console.log(res);
    });
  }
}

```

My angular2-token version is v0.1.17.

**Comment by neroniaky** [comment]
Hey @olpdev7, angular2-token wraps the same http service you're using in your workaround. Have you tried using the newest beta v0.2.0? 

You can take a look at a working example for form submissions at the example repository [here](https://github.com/neroniaky/angular2-token-example).

**Comment by artem-galas** [comment]
Hi!

Yes, we tried using the new version but still did not succeed  in sending FormData object within `.put` method.
As we need to send an avatar for a user, we do not have other options but sending FormData.

We’ve found a solution by sending a regular `http.put` request with necessary headers, but have faced a different issue - `this._curentAuthData` doesn’t update if a request was sent with a regular http instead of  using  `tokenSerivice` wrapper, which means after user update, we send a request to `validateToken` and get invalid, as headers are sent with an old token instead of the new one that was updated after the request.

**Comment by kouichitanaka726** [comment]
Hi @artem-galas I'm having the same issue. Have you solved it already? I would like you to share the solution if you have. Thanks.

**Comment by artem-galas** [comment]
@kouichitanaka726 Unfortunately, no. Now user is being logged out once they change an avatar. If @neroniaky tells me where I should look at, I would be glad to improve this package :)

**Comment by artem-galas** [comment]
Hi @neroniaky . I really need help here :)

I figured out what should be done to solve the issue I am having. I need to pass the following headers:
`'Content-Type':'multipart/form-data'`
As far as I understood, they should be passed using `RequestOptionsArgs` parametr in your http wrapper methods.

But I do not understand how I can do this. 
Can you please explain this? As the code below causes such error: 

```bash
ERROR in /Users/artemgalas/ROR/galas-angular2-token-test/src/app/app.component.ts (35,51): Argument of type 'RequestOptionsArgs' is not assignable to parameter of type 'RequestOptionsArgs'.
  Types of property 'search' are incompatible.
    Type 'string | URLSearchParams' is not assignable to type 'string | URLSearchParams'.
      Type 'URLSearchParams' is not assignable to type 'string | URLSearchParams'.
        Type 'URLSearchParams' is not assignable to type 'URLSearchParams'.
          Types have separate declarations of a private property 'queryEncoder'.)
```
CODE

```ts
  public sendFormData() {
    let fd:FormData = new FormData();
    fd.append('avatar', 'blob', 'blob name');
    let headers: Headers = new Headers({'Content-Type':'multipart/form-data'});
    let roa: RequestOptionsArgs = new RequestOptions({headers: headers});
    console.log(roa);

    this.tokenService.post('/send_form_data', fd, roa)
      .subscribe(res => console.info(res), err => {console.warn(err)});
  }
```

**Comment by osazemeu** [comment]
Am facing same issue!

**Comment by Senegal** [comment]
you can use "request" method and append auth headers with {enctype: "multipart/form-data"}

example from my user-service class
`  
export class UserService extends Angular2TokenService {
 ......
  updateMediaImage(model, id, value){
    let fd:FormData = new FormData();
    fd.append('media', value, 'image.png');
    let hdrs = this.currentAuthHeaders;
    hdrs.append('enctype',"multipart/form-data")
    let requestOptions = new RequestOptions({
      method: RequestMethod.Put,
      headers: hdrs,
      url: environment.apiEndpoint+'/media/'+model+'/'+id,
      body: fd
    });
    return this.request(requestOptions).toPromise().then(
        (response) => response.json()
    );
  }
.......
}
`

**Comment by neroniaky** [comment]
Should be fixed in version 6.0 with the use of interceptors. Please reopen if still an issue.

**Comment by NiekPas** [comment]
@neroniaky I'm still having the same issue on `angular@6.0.6` and `angular2-token@0.2.0`

**Comment by arjenbrandenburgh** [comment]
@NiekPas, he means using version 6.0.0-rc.0 of angular-token

https://github.com/neroniaky/angular2-token/tree/6.x
https://www.npmjs.com/package/angular-token
