### ISSUE TITLE
ERROR in A2tUiModule is not an NgModule

### ISSUE THREAD

**Issue by software-project** [neroniaky/angular2-token#138]
I'm getting this error on server startup `ERROR in A2tUiModule is not an NgModule`

**Comment by neroniaky** [comment]
Can you tell me which framework/bundler you're using?

**Comment by software-project** [comment]
Angular CLI, when I downgraded CLI it worked.

**Comment by neroniaky** [comment]
So it doesn't work with which version then?

**Comment by software-project** [comment]
With 1.0.0-beta.25.5 it raise that exception. With 1.0.0-beta.20-4 it's fine.

**Comment by bluegod** [comment]
Same problem here, using Angular CLI `1.0.0-beta.26`- haven't tried downgrading yet.

**Comment by neroniaky** [comment]
Gonna take a look into it. Need to update my Angular CLI first.

**Comment by neroniaky** [comment]
Seems to be a problem with angular-cli and its dependencies [here](https://github.com/angular/angular-cli/issues/3426). 
For the development it still works on the second compile. Haven't tested publishing yet.

**Comment by bluegod** [comment]
Hmm looks like it has to do with the metadata? https://github.com/angular/angular-cli/issues/4447#issuecomment-277813492

In that issue, they also figured out it works after recompiling in dev mode

**Comment by neroniaky** [comment]
@bluegod yeah I read some other issue that said the problem disappeared after changing the build process.

**Comment by davidjconnolly** [comment]
Is the only workaround to this to downgrade to CLI 1.0.0-beta.20-4?  I'm on 1.0.0-beta.32.3 and it's still happening with `ng serve`:

```
ERROR in A2tUiModule is not an NgModule
webpack: Failed to compile.
```

**Comment by neroniaky** [comment]
@davidjconnolly or ignoring the first compile. I probably gonna have to change the build process to fix this.

**Comment by bluegod** [comment]
I can't find a workaround for building in production though... `ng build --aot --target=production --environment=prod`

**Comment by bluegod** [comment]
For the record, I managed to _fix_ the issue in development doing the following:

* Clone `angular2-token` repo locally.
* Run `node_modules/.bin/ngc tsconfig.json`
* Copy all generated `.metadata.json` files into the corresponding `angular2-token` folder in the `node_modules` folder of your app.

This is obviously a temporary solution. I can now run `ng serve` and no error is thrown. However, I have now a new issue (perhaps unrelated) building in production:

```
ERROR in vendor.4207944964f016799cfe.bundle.js from UglifyJs
SyntaxError: Unexpected token name «i», expected punc «;» [vendor.4207944964f016799cfe.bundle.js:97289,13]
```

Looks like something related to UglifyJS, but I have no idea how to debug that further.

**Comment by neroniaky** [comment]
I just published beta.9, which includes the `*.metadata.json` files. Would be great if someone would give it a try.

**Comment by bluegod** [comment]
Thanks @neroniaky - I tested it and I see no more `ERROR in A2tUiModule is not an NgModule`. I think you can close this issue now.

**Comment by davidjconnolly** [comment]
@neroniaky thanks for the quick fix!  That addresses the `ERROR in A2tUiModule is not an NgModule` issue as @bluegod, however I've found a new issue.

After I log in, if I refresh (Using `CMD-R`) from within my app, the app crashes with the following error:
```
EXCEPTION: Uncaught (in promise): TypeError: Cannot read property 'signInStoredUrlStorageKey' of undefined
TypeError: Cannot read property 'signInStoredUrlStorageKey' of undefined
    at Angular2TokenService.canActivate (http://localhost:4200/vendor.bundle.js:16554:30)
    at MapSubscriber.project (http://localhost:4200/vendor.bundle.js:25128:138)
    at MapSubscriber._next (http://localhost:4200/vendor.bundle.js:17282:35)
    at MapSubscriber.Subscriber.next (http://localhost:4200/vendor.bundle.js:6191:18)
    at ArrayObservable._subscribe (http://localhost:4200/vendor.bundle.js:71901:28)
    at ArrayObservable.Observable._trySubscribe (http://localhost:4200/vendor.bundle.js:721:25)
    at ArrayObservable.Observable.subscribe (http://localhost:4200/vendor.bundle.js:709:27)
    at MapOperator.call (http://localhost:4200/vendor.bundle.js:17259:23)
    at Observable.subscribe (http://localhost:4200/vendor.bundle.js:706:22)
    at MergeAllOperator.call (http://localhost:4200/vendor.bundle.js:49423:23)
    at Observable.subscribe (http://localhost:4200/vendor.bundle.js:706:22)
    at EveryOperator.call (http://localhost:4200/vendor.bundle.js:72496:23)
    at Observable.subscribe (http://localhost:4200/vendor.bundle.js:706:22)
    at Object.subscribeToResult (http://localhost:4200/vendor.bundle.js:35646:27)
    at MergeAllSubscriber._next (http://localhost:4200/vendor.bundle.js:49445:42)
```

It stems from this code where it appears this._options is undefined:
```
// Store current location in storage (usefull for redirection after signing in)
if (this._options.signInStoredUrlStorageKey) {
    localStorage.setItem(this._options.signInStoredUrlStorageKey, window.location.pathname + window.location.search);
}
```

I've initialized _tokenAuth per the Readme in my AppComponent:
```
this._tokenService.init({
   apiBase: url
});
```

I'm able to login and use my app as expected, however whenever I refresh, I get the error mentioned above.  Curiously, this only occurs when I'm not on my root /#/ path.

Any suggestions?

**Comment by neroniaky** [comment]
@davidjconnolly looks to me like [#159](https://github.com/neroniaky/angular2-token/issues/159)

**Comment by davidjconnolly** [comment]
@neroniaky thanks!  That was it exactly, downgrading to "@angular/router": "3.2.1" fixed the issue for me.
