### ISSUE TITLE
Security Issue - Wrong logic of validation

### ISSUE THREAD

**Issue by vinsy** [neroniaky/angular2-token#139]
I am able to access restricted site even if I send wrong auth headers. You are supposed to validate token from server not just if they are present in local storage before allowing access.

Steps to reproduce:

https://angular2-token.herokuapp.com/

1. Create an account
2. Login
3. from chrome console access local storage & change its value anything you want.
4. click on restricted site.

**Boom!! you can access it.** I was stucked on this one for at least 3-4 hours, have to debug & understand each line of your code. It might have been better if I would have written my own logic.

**Suggested Fix:**  Currently it is returning boolean from canActivate method. Won't it be better if we return Observable<boolean> based on the response of validate_token from server.

As per Angular 2 official doc - canActivate can return one of these : `Observable<boolean>|Promise<boolean>|boolean`

**Comment by adonespitogo** [comment]
Did you try to return 403 or 401 response on the restricted resource? I haven't tried this but I think this module handles unauthenticated responses from the server automatically

**Comment by neroniaky** [comment]
Hey @vinsey, thanks for your feedback. 

Unfortunately you don't seem to understand how a Frontend Library like this works. Please read up on Devise and the underlying devise token with. 

Gonna close this for now, because this came up multiple times already and isn't a bug.

**Comment by vinsy** [comment]
I might be new to this type of client side authentication but I really couldn't understand how a user can activate routes, even if validate token response is still pending from server.

`    userSignedIn(): boolean {
        return !!this._currentAuthData;
    }`

Above code just check `_currentAuthData` from local storage.

As per this github issue, correct way to validate is return true only after complete validation or return observable<boolean>
https://github.com/angular/angularfire2/issues/282

I am not justified. Could you please provide me link where I can read about this type of validation, it would be a great help!

**Comment by neroniaky** [comment]
@vinsy I'm working on an FAQ, which will include this question.
