### ISSUE TITLE
[Question] Compatibility with other Identity Providers

### ISSUE THREAD

**Issue by lgleim** [neroniaky/angular2-token#146]
Is this service compatible with other Identity Providers such as a generic OpenID Connect Server? Maybe Keycloak? If yes, how would it be configured for such a use case?

**Comment by neroniaky** [comment]
Hey @lgleim I guess the underlying logic is compatible, but I didn't look into making it compatible to the services you listed, yet. It's on my ToDo-List tough 😄 .

**Comment by lgleim** [comment]
Great to hear! Since OpenID Connect is a standardardized protocol, it will allow angular2-token to be used with a plethora of Identity Providers. Do you have an actual Roadmap/time-frame in mind? Or is this currently just out there as a todo for later?

**Comment by neroniaky** [comment]
@lgleim unfortunately I'm quite busy recently, so I don't think I can commit to any timeline.

PR's are always welcome 😉 .
