### ISSUE TITLE
404 when Signing out

### ISSUE THREAD

**Issue by ebosantos** [neroniaky/angular2-token#147]
I'm dealing with 404 not found when trying to sign out:

`Started DELETE "/v1/auth/sign_out"` -> `Completed 404 Not Found`

I've read somewhere this happens when request doesn't send auth params (access-token, uid, etc).

Looking at code, this makes completely sense:

```
signOut(): Observable<Response> {
        let observ = this.delete(this._getUserPath() + this._options.signOutPath);

        localStorage.removeItem('accessToken');
        localStorage.removeItem('client');
        localStorage.removeItem('expiry');
        localStorage.removeItem('tokenType');
        localStorage.removeItem('uid');

        this._currentAuthData = null;
        this._currentUserType = null;
        this._currentUserData = null;

        return observ;
    }
```

Probably you will can remove keys from localstorage only when the DELETE request get completed.

A not tested suggestion would be:

```
signOut(): Observable<Response> {
        let observ = this.delete(this._getUserPath() + this._options.signOutPath);

        observ.subscribe(res => {
                localStorage.removeItem('accessToken');
                localStorage.removeItem('client');
                localStorage.removeItem('expiry');
                localStorage.removeItem('tokenType');
                localStorage.removeItem('uid');

                this._currentAuthData = null;
                this._currentUserType = null;
                this._currentUserData = null;
        }); 

        return observ;
    }
```

If it doesn't make sense, please let me know.

**Comment by neroniaky** [comment]
@ebosantos you're completely right. I did it this way, so that logout works always. Looking at the ng-token-auth implementation, we should probably change it to observable, like you're suggesting. Care to create a PR? Thanks!

**Comment by osazemeu** [comment]
I am encountering same issue, checkout the link below. 
http://stackoverflow.com/questions/32507637/why-am-i-unable-to-sign-out-using-devise-token-auth-and-curl

**Comment by arjenbrandenburgh** [comment]
This is fixed in version 6 onward.
