### ISSUE TITLE
Is there ability to handle session timeout

### ISSUE THREAD

**Issue by outsourcegb** [neroniaky/angular2-token#155]
Was wondering if there is ability to handle session timeout. 

I have issue that if we don't logout and check the application after a day or two it finds user is logged out but it doesn't redirect it to login page.

**Comment by neroniaky** [comment]
Have you tried setting `signOutFailedValidate`?

**Comment by outsourcegb** [comment]
Yes, it works when we refresh page but it doesn't work when we have application open in the tab somewhere and try to access it. 

Also, sometimes signOutFailedValidate doesn't work when we write url directly.

**Comment by neroniaky** [comment]
The default timeout for Devise is 2 weeks, so leaving a tab open for this long is quite unlikely (I guess :) ). I think there are two ways to solve a short timeout. Let me know if I understand it correctly. 

1. Periodic calls of ".validateToken()".
2. Logout on failed Http-Request, which in my experience leads to many problems.

**Comment by outsourcegb** [comment]
I am not sure about 2 weeks, but it gets time out before. Its not confirmed but will check about that time.

About calling .validateToken(), yes its there but still I wasn't sure if there is direct way in package that can handle that. 

Logout on failed request, agree that will lead.

**Comment by neroniaky** [comment]
You can modify the lifespan in the `devise_token_auth.rb`. 

```
  # By default, users will need to re-authenticate after 2 weeks. This setting
  # determines how long tokens will remain valid after they are issued.
  # config.token_lifespan = 2.weeks
```

**Comment by martinechtner** [comment]
@neroniaky When a session times out and 401 is returned from the api, how would I automatically redirect to sign-in?

Currently if a session times out I refresh the page manually:
- it reloads the page I was on
- no data is returned as the session is in a invalid state

If I refresh the page again then I am redirected to sign in.

**Comment by neroniaky** [comment]
You can set signInRedirect() for an automatic redirect.
