### ISSUE TITLE
canActivate called before init

### ISSUE THREAD

**Issue by jdrunner** [neroniaky/angular2-token#159]
After upgrading to **@angular/core 2.4.8**, **@angular/router 3.4.8** the angular2-token Route Guards stop working. It looks like the router is checking the` canActivate` parameter before the app component calls `init` on the angular2-token service.

route declaration:

```
const routes: Routes = [
  {
    path: '',
    redirectTo: 'home',
    pathMatch: 'full',
    canActivate: [Angular2TokenService]
  },
```

app component:
```
constructor(
    private tokenService: Angular2TokenService,
  ) {    
    //configure angular2-token
    tokenService.init({
      apiPath: 'http://localhost:3000',
      //... more parameters
    })
  }
```

The page fails to load when it hits the following line of `canActivate`:

` if (this._options.signInStoredUrlStorageKey) `

with `this._options` is undefined. This is because `init` has not been called yet.

This might be a side effect of [#14327](https://github.com/angular/angular/pull/14327)

**Comment by neroniaky** [comment]
Thanks @jdrunner for your detailed description. Looks like an issues with angular [#14588](https://github.com/angular/angular/issues/14588#issuecomment-280907352) to me.

**Comment by neroniaky** [comment]
Angular published v2.4.9 which reverted the change. Gonna close this for now. You can reopen the issue if the problem persists.

**Comment by dancancro** [comment]
Hi all. I'm working on [this](https://github.com/dancancro/great-big-angular2-example/tree/fixauth/src/app/core/auth) project and having this problem with Angular 2.4.9, & angular2-token 0.2.0-beta.11

**Comment by neroniaky** [comment]
Something about the order got changed again [see Angular Changelog](https://github.com/angular/angular/blob/master/CHANGELOG.md), not sure if it has any influence.

@dancancro do you know how other libraries solve this problem? Should be common..I guess?.

**Comment by dancancro** [comment]
@neroniaky sorry, I don't know that. 

I'm not sure where in the change log you find this reordering - Do you mean here? 
"core: call lifecycle hooks for siblings in declaration order"
