### ISSUE TITLE
Adding extra registration fields

### ISSUE THREAD

**Issue by evanhdc** [neroniaky/angular2-token#162]
I went through the documentation but couldn't figure this out. I'd like to add more fields to the sign up page like
* email
* password
* passwordConfirmation
* first name
* last name
* DoB
But I got a "property_name doesn't not exist in type RegisterData" error when I try to add first name, last name and DoB to .registerAccount().

I took a look at RegisterData and it only includes email, password, passwordConfirmation, name and userType (see below):
export interface RegisterData {
    email: string;
    password: string;
    passwordConfirmation: string;
    name?: string;
    userType?: string;
}

Is it possible to extend so I can send more fields to the backend? Thank you in advance!

**Comment by neroniaky** [comment]
@evanhdc thanks for your issue. This commit should allow you to add more data to the hash for `.registerAccount()`.

**Comment by johnpmitsch** [comment]
@neroniaky I would love to use this in my app,  when do you think it will be included in a release?

**Comment by michaelharris7** [comment]
I don't see how this is working. I can save the email and password just fine as it should work, but I can't save the name field that should be included and I can't save any newer customized registration fields like full_name.

It doesn't give me an error and the console looks like it saves just fine, but when I check the User account in my rails console, it shows nil for full_name.
