### ISSUE TITLE
There is no oAuthHost option

### ISSUE THREAD

**Issue by Kris-Simpson** [neroniaky/angular2-token#167]
Visual Studio Code shows, that option `oAuthHost` is not present in `Angular2TokenOptions`

![screenshot at 18-12-46](https://cloud.githubusercontent.com/assets/2270584/23267549/bdf00f6c-f9f3-11e6-95d5-1dbb3db4b6c9.png)

package version: 0.2.0-beta.8 (0.2.0-beta.6 has the same error)

I checked package folder, there is really no such option:

![screenshot at 18-14-36](https://cloud.githubusercontent.com/assets/2270584/23267640/08096634-f9f4-11e6-90bc-ee67de8553ae.png)

**Comment by neroniaky** [comment]
@Kris-Simpson its named oAuthBase not oAuthHost. Thanks spotting this!
