### ISSUE TITLE
MockBackEnd backend for development unsing local json files

### ISSUE THREAD

**Issue by norato** [neroniaky/angular2-token#168]
I need to code my app without backend using local json files.
I used [ng-token-auth](https://github.com/lynndylanhurley/ng-token-auth) in a previous project and it worked very well.
``` javascript
    constructor(private _tokenService: Angular2TokenService) {
        this._tokenService.init({
           apiPath: this.endPointUrl
        });
    }
```
When I'm using `rails server` it's running *ok*, but using my local `validate_token.get.json`(as a simple copy of rails server log) is not working running this console error.
![image](https://cloud.githubusercontent.com/assets/395588/23272448/0a8a8650-f9da-11e6-93e2-6a2d490fc71b.png)

Who knows how can I solve it?

**Comment by neroniaky** [comment]
Looks like a problem with your CORS configuration to me. Did you check [here](https://github.com/neroniaky/angular2-token#cors-configuration)?

**Comment by norato** [comment]
@neroniaky I created a express backend to simulate it. We need a more complex mockup.
Thanks for your feedback!
