### ISSUE TITLE
Use Angular2 RouterStateSnapshot for URL redirect value

### ISSUE THREAD

**Issue by jasonmscollins** [neroniaky/angular2-token#171]
Rather than using the window.location.pathname variable it might be better to use the RouterStateSnapshot state.url value when getting the current location for redirection after sign in.

I found this as an example. 
http://jasonwatmore.com/post/2016/12/08/angular-2-redirect-to-previous-url-after-login-with-auth-guard

**Comment by neroniaky** [comment]
Fixed in version 6.0. Thank you for your feedback!
