### ISSUE TITLE
The a2t-ui don't generates the view files and .ts files

### ISSUE THREAD

**Issue by EduMaca** [neroniaky/angular2-token#173]
![imageedit_2_6058147627](https://cloud.githubusercontent.com/assets/16768539/23524091/fcfa4460-ff67-11e6-8980-ac43c29f1224.png)
So i installed the angular2-token and all the functionality are fine.
But, when i want to change the a2t-ui files, for my surprise, there are no html or .ts files on the folder, only the declarations files.

Can anyone help me please?

My nodejs version is: 7.6.0
npm version: 4.1.2
os: linux ubuntu

**Comment by neroniaky** [comment]
@EduMaca thanks for you explanation. Gonna take a look into it.

**Comment by neroniaky** [comment]
The packages is compiled for AoT, thats why there are no TS files. The HTML and CSS is included in the .js files as well.
