### ISSUE TITLE
Incompatible with Angular 4 AOT compilation

### ISSUE THREAD

**Issue by avatsaev** [neroniaky/angular2-token#194]
Angular2 Token is incompatible with Angular 4 Ahead Of Time compilation 

```
/node_modules/angular2-token/lib/a2t-ui/a2t-sign-in/a2t-sign-in.component.ngfactory.ts (1,1): Property '_errors' is private and only accessible within class 'A2tSignInComponent'.

```

**Comment by neroniaky** [comment]
@avatsaev Thanks! Working on it right now 😄 .

**Comment by avatsaev** [comment]
Oh just forked it to fix lol, need help?

**Comment by neroniaky** [comment]
Gonna give it a try first. Will let you know if I run into any problems. Thanks!

**Comment by avatsaev** [comment]
Tested, seems to be working on this branch? Do you want me to PR?  https://github.com/avatsaev/angular2-token/tree/angular4-aot

**Comment by neroniaky** [comment]
Perfect Thanks. Can you remove the "public" and give the PR a proper name? That would be awesome.

**Comment by avatsaev** [comment]
Ok, 

> Can you remove the "public"

what do you mean?

**Comment by neroniaky** [comment]
`private _emailSend: boolean = false;` -> `_emailSend: boolean = false;` should be sufficient.

**Comment by avatsaev** [comment]
got it

**Comment by avatsaev** [comment]
Thanks for the merge, when will you publish on NPM?

**Comment by neroniaky** [comment]
As soon as I tried it with the example project. I'm on it now.

**Comment by avatsaev** [comment]
Ok keep me posted 👍🏻

**Comment by avatsaev** [comment]
Looks reassuring https://github.com/neroniaky/angular2-token/commit/17a6c7aa69dc4623554c63bee5ad18aa517de1d0#commitcomment-21473371
