### ISSUE TITLE
localStorage not set when I set apiBase upon _tokenService.init()

### ISSUE THREAD

**Issue by venomoustoad** [neroniaky/angular2-token#198]
I have a rails BE application on localhost:3000 and FE on localhost:4200. I am trying to get the token validation to be done automatically and I understand this happens through localStorage being set and retrieved during the _tokenService.validateToken() method. The problem seems to be that once I sign in (successfully), I looked at my localStorage in my browser and found nothing saved. Hence, when I refresh the page, there is no localStorage to validate as a part of my validateToken() method and hence, the session is not maintained on the browser. What am I missing here? Is there a mistake in the way I have initialised this command? Do I need to manually set the localStorage everytime? If so, how? 

I tried a simple app where my  app.component.ts has the following
```
import { Component, ViewEncapsulation, OnInit } from '@angular/core';
import { Angular2TokenService } from 'angular2-token';
@Component
....
export class AppComponent {
    constructor(private _tokenService: Angular2TokenService) {
         this._tokenService.init({apiBase:'http://localhost:3000'});
    }
}
```
My Sign-in (sign-in.component.ts)
```
import { Component, OnInit } from '@angular/core';
import { Angular2TokenService, SignInData } from 'angular2-token';

@Component({
    selector: 'sign-in',
    templateUrl: 'sign-in.component.html'
})
export class SignInComponent {

    private _signInData: SignInData = <SignInData>{};
    private _output: any;

    constructor(private _tokenService: Angular2TokenService) { }

    // Submit Data to Backend
    onSubmit() {

        this._output = null;

        this._tokenService.signIn(this._signInData).subscribe(
            res => {
                this._signInData    = <SignInData>{};
                this._output        = res;
            }, error => {
                this._signInData    = <SignInData>{};
                this._output        = error;
            }
        );
    }
}
```

**Comment by venomoustoad** [comment]
After much searching and trial and error, the solution was in setting a proxy for specific routes. This can be done by adding the following file in the root directory of your angular application


> proxy.config.json

```
{
  "/auth": {
    "target": "http://localhost:3000",
    "secure": false
  }
}
```
also include this in your

> package.json

```
{
..
..
  "scripts": {
  ...
  ...
  "start": "ng serve  --proxy-config proxy.conf.json",
  ...
  ...
  }
..
..
}
```
This issue fundamentally was that response headers sent were not getting allocated to my browsers localStorage through the following command

`this._tokenService.init({apiBase:'http://localhost:3000'});`
changed this back to

`this._tokenService.init(); `
And instead routed all request through the /auth default routes set in the angular2-token through a proxy request to the corresponding rails routes.

**Comment by neroniaky** [comment]
@venomoustoad thanks a lot for your detailed explanation. 

The way I solved this in the example repository ([here](https://github.com/neroniaky/angular2-token-example/blob/master/angular2-client/proxy.conf.json)) is to use hash style routing and this proxy.conf:

```
{
  "**": {
    "target": "http://localhost:3000",
    "secure": false
  }
}
```

**Comment by venomoustoad** [comment]
Sure np. I tried your solution as well. The problem I faced was considering I had already defined a whole set of assets in my FE application and when I set a ** proxy, it was trying to load everything from my BE instead. Hence, i had to include the api routes uniquely.

**Comment by raysuelzer** [comment]
I am having a similar issue.  I have the proxy set up and working, and can see localStorage being set in my browser, but getAuthDataFromStroage is returning null. 

![image](https://user-images.githubusercontent.com/1176341/31260728-b9fa0ae0-aa04-11e7-952f-dfde6323eb30.png)

**Comment by raysuelzer** [comment]
This was an error my end. I had two instances running.

**Comment by tomuench** [comment]
i had the same problem with a rails api. I couldn't run my app with a proxy, so i have digged a bit deeper.

My Solution was, to allow the used headers explicit.
Example:
`    resource '*',
             headers: :any,
             methods: %i[get post put patch delete options head], 
             :expose => ['access-token', 'client', 'expiry','token-type', 'uid']`

Hope this helpes somebody in the future.
