### ISSUE TITLE
userSignedIn

### ISSUE THREAD

**Issue by suthaRavi** [neroniaky/angular2-token#202]
userSingedIn return false after successful login.

**Comment by venomoustoad** [comment]
this might be the same issue - you could try the solution here
https://github.com/neroniaky/angular2-token/issues/198

**Comment by neroniaky** [comment]
Can't reproduce error. Could you provide a more detailed description?

**Comment by suthaRavi** [comment]
hi

kindly look the following details:



Back end Rails 5 and  devise token auth

front end Angular 2 and Angular2 token auth

After login,

        login is success but

*.userSignedIn() returns false*


logout returns error like this

  ERROR Object { _body: "{"errors":["User was not found or w…",
status: 404, ok: false, statusText: "Not Found", headers: Object, type: 2,
url: "http://localhost:3000/auth/sign_out" }


*the above solution #198 is not working for me.*

Thanks for your help'

Ravi

**Comment by suthaRavi** [comment]
I solved the problem.
The problem is from back end, access token not send to client.

Thanks

**Comment by suthaRavi** [comment]
Hi

How can I use a2t ui.

I really appreciate for your help.

Thanks
