### ISSUE TITLE
Send query to subdomain

### ISSUE THREAD

**Issue by artem-galas** [neroniaky/angular2-token#25]
Hi!
Do we have a possibility to send a query with `_tokenService` to subdomain?

**Comment by neroniaky** [comment]
Hey @artem-galas, gonna take a look into it. Did not test this case yet.

**Comment by artem-galas** [comment]
@neroniaky Thanks :)

**Comment by artem-galas** [comment]
As the subdomain for the client and the API is the same, I made this trick on AppComponent:

```javascript
    let result: any;
    result = {};
    let regexParse = new RegExp('([a-z\-0-9]{2,63})\.([a-z\.]{2,5})$');
    let urlParts = regexParse.exec(window.location.hostname);
    result.domain = urlParts[1];
    result.type = urlParts[2];
    result.subdomain = window.location.hostname.replace(result.domain + '.' + result.type, '').slice(0, -1);

    let query_url = 'http://${result.subdomain}.${Config.PATH}';

    this._tokenService.init({
      apiPath: query_url
    });
```

**Comment by neroniaky** [comment]
I just uploaded v0.1.12. With this you should have two options to access a subdomain.

1. Don't specify `apiPath` and enter the full domain name for the HTTP Wrapper methods like `.get('http://mysubdomain.domain.come/my-resource')`
2. Use `.sendHttpRequest()` which gives you full control over what should be send. Details [here](https://github.com/neroniaky/angular2-token#sendhttprequest).

Would be nice if you could give it a try and tell me if that works for you. Thanks!

**Comment by neroniaky** [comment]
Closing because no answer in 7 days. If you have further questions/remarks you can use the Gitter Chat.
