### ISSUE TITLE
Configurating sign-in component in a2t-ui

### ISSUE THREAD

**Issue by er-ant** [neroniaky/angular2-token#258]
Hello. Is it any way to config links in sign-in component? In my project only administrator can register anybody, so i don't want to display 'sign up' link on the first screen.

**Comment by Verurteilt** [comment]
Hello @er-ant, I don't think this is an issue with the library, whan you can do is do not add a signup button on the first screen, then on the Route for the signup validate if the used is loged and if he is an administrator, you can do this in both backend and frontend.

**Comment by er-ant** [comment]
@Verurteilt I am about configuring default a2t-ui module.

**Comment by neroniaky** [comment]
Thanks @Veruteilt.

The Module is supposed to be for an easy start only, it is therefore not configurable. You can roll your own "quick start" by cloning the example repo.
