### ISSUE TITLE
Not staying logged in across a refresh

### ISSUE THREAD

**Issue by denishaskin** [neroniaky/angular2-token#259]
From reading other issues and the doc, it does sound like a user *should* stay logged in after a page refresh, but I can't get that to work.

This is a pretty standard angular-cli Angular 2 app, using an auth guard.

What I find a little weird is that after I have logged in successfully, even if I inspect `localStorage` (and `sessionStorage`, for that matter) using Chrome dev tools I don't see any of the `angular2-token` keys.  Which would explain why a page refresh causes a redirection to the login component.

At the moment, the only call I have to any of the `angular2-token` API is to `signIn()`, and it authenticates successfully against my devise backend and I see the `access-token`, `client`, etc keys in the returned headers to the `/auth/sign_in` call.

I can try to put together a stripped-down version of an app that demonstrates this, but is there something obvious I am likely missing?

**Comment by victorct** [comment]
Hello @denishaskin  could you provide us with something we can work with? We might not be able to give you a solution without some code first.

**Comment by neroniaky** [comment]
My guesses:
1. Missing .init() in main Component
2. CORS configuration

**Comment by denishaskin** [comment]
@neroniaky I have the `.init()` in my own auth service, is it a requirement that it be in a main component?

Can you clarify what you mean by CORS configuration?  I *am* correctly getting authenticated and it all works fine until I refresh the page.

I've been away from this project for a bit but I'm putting together a sample app now.

Thanks!

**Comment by denishaskin** [comment]
Okay, I think I had 2 issues.

First, yes, my back-end CORS config wasn't allowing the relevant headers to be accessed, and so auth info was never getting written to local storage by `angular2-token`.

Second, I ended up `.init()` ing the `angular2-token` service both in the main Component *and* in the AuthGuard, which seemed to be the main issue for the refresh.
