### ISSUE TITLE
Not refreshing atCurrentAuthData

### ISSUE THREAD

**Issue by Bernica** [neroniaky/angular2-token#260]
Hi !

I've been having an issue with the "session" when using multiple tabs, and in rare cases (not reproducible yet) when using just one too.

After digging into the library code, I found the following problem: At angular2-token.service, when making a new request, it checks for `this.atCurrentAuthData != null` but this local variable may have old data, as another request from another app (like the same app in another tab) may have updated the localStorage with new data.

One solution could be to just read and write from and to localStorage directly. Another possibility could be to check if the local variable's data is updated before using it (it needs one read from localStorage anyways).

Hope it helps anybody and thanks for developing this library.

**Comment by volpejoaquin** [comment]
I found a simple solution adding only one line:

```
// Get at current auth data from local storage
this.getAuthDataFromStorage();
```

`Angular2TokenService.prototype.request = function (options) {
      let baseRequestOptions;
      let baseHeaders = this.atOptions.globalOptions.headers;
      // Get at current auth data from local storage
      this.getAuthDataFromStorage();
      // Merge auth headers to request if set
      if (this.atCurrentAuthData != null) {
        Object.assign(baseHeaders, {
            'access-token': this.atCurrentAuthData.accessToken,
            'client': this.atCurrentAuthData.client,
            'expiry': this.atCurrentAuthData.expiry,
            'token-type': this.atCurrentAuthData.tokenType,
            'uid': this.atCurrentAuthData.uid
        });
      }
      console.log(this.atCurrentAuthData);
      baseRequestOptions = new RequestOptions({
          headers: new Headers(baseHeaders)
      });
      // Merge standard and custom RequestOptions
      baseRequestOptions = baseRequestOptions.merge(options);
      let response = this.http.request(new Request(baseRequestOptions)).share();
      this.handleResponse(response);
      return response;
    };`

**Comment by neroniaky** [comment]
Hey @Bernica thanks for point out this problem.

@volpejoaquin sound like a good solution to me. The library currently only checks the storage once on startup. Care for a PR?
