### ISSUE TITLE
impersonate another user?

### ISSUE THREAD

**Issue by denishaskin** [neroniaky/angular2-token#289]
I'd like to let an admin user "impersonate" another user, and I'm trying to figure out how best to do this (and whether `angular2-token` can support this without modifications).  (I'm using the `devise_token_auth` gem on the back end, fwiw.)

I've already got the client-side logic so that if I'm an admin I can set a flag in my `User` object that I'm impersonating a user and who the impersonated user is.  I guess I'll probably add another header to all requests which is the impersonated-user-id, and add a `before_action` on the back end that if the actual user is an admin and an `impersonated-user-id` header is present, set the current user to the impersonated user for this request.

Better way?

**Comment by neroniaky** [comment]
Hey @denishaskin , this would be a nice feature to have. Haven't tried it yet though 😄 .

I'm not sure if I understand your approach correctly, but you should always remember that there is no security in the client side, so everything should be handled by the backend.

It largely depends on which kind of admin implementation you are using in your Backend. You could go the CanCan route, or with an seperate admin model (rails) and different routes.

Your approach is to handle two sets of header data, which is basically the only thing angular2-token does (for one set). So the idea would be to use two instances of this library at the same time. But how they communicate or if it actually works, no idea.
