### ISSUE TITLE
Angular 4.3.x HttpClient compatibility

### ISSUE THREAD

**Issue by timorthi** [neroniaky/angular2-token#309]
Are there any plans to upgrade this service to support Angular 4.3.x's `HttpClient`? 

[Commit describing the change](https://github.com/angular/angular/commit/37797e2)
[Official docs](https://angular.io/guide/http)

**Comment by neroniaky** [comment]
Hey @xozzo, sure. Working on it, but as far as I can tell, it will be quite some work.

**Comment by xozzo** [comment]
@neroniaky Is there an active branch? I'm interested in contributing. :)

**Comment by neroniaky** [comment]
@xozzo just pushed the branch httpclient. Enjoy :).

**Comment by xozzo** [comment]
@neroniaky I think I've got a rough idea of the changes that need to be made - do we want to keep the service backwards compatible for those who are using <4.3?

**Comment by neroniaky** [comment]
As far as I can tell now, being backward compatible will add a lot of complexity. What do you think?

**Comment by xozzo** [comment]
Yeah, I agree. The new `@angular/common/http` module introduces [HttpInterceptor](https://angular.io/guide/http#intercepting-all-requests-or-responses) which eliminates the need for a2token to implement http method wrappers. If you really wanted to, maybe we can determine which Http module to use based on [version obtained at runtime](https://github.com/angular/angular/issues/1357)?

**Comment by mrsweaters** [comment]
This looks good. The typings still point to `lib` instead of `src` in:
https://github.com/neroniaky/angular2-token/blob/httpclient/angular2-token.d.ts

**Comment by Uelb** [comment]
Hi,
Is there a quick workaround to implement an HTTP interceptor around the angular 2 token service http wrapper ? I was thinking about extending the service class and redefining the handleResponse method, but I was wondering if there would be a simpler way while waiting for this branch to be available.

**Comment by rmcsharry** [comment]
It would be awesome if this branch could be merged, interceptors are awesome! :)

**Comment by NaraR2** [comment]
Any advance on this? Will be really good to have this merged.

**Comment by dikey94** [comment]
guys, any progress in the topic?

**Comment by minhthuan274** [comment]
Any update ?

**Comment by glebmachine** [comment]
up?

**Comment by timorthi** [comment]
AFAIK, nobody is working on this right now. @NaraR2 @minhthuan274 @glebmachine

**Comment by colmben** [comment]
Just for the sake of people commenting asking for the branch to be merged, there is no actual new code in the branch! All it has is a tweak to the Readme saying the branch is experimenting with HttpClient :(

With HttpModule now deprecated, this service really needs to move to HttpClient at some point. It gives a huge advantage in that we could use interceptors to stop wrapping the http methods and so 3rd party libraries that hide http access (like Restangular) will work. This is how the AngularJS devise token lib works (https://github.com/lynndylanhurley/ng-token-auth).

**Comment by proxygear** [comment]
Hi,
I'm thinking about working on this, at least trying :)

However, after cloning, I wasn't able the run test : https://github.com/neroniaky/angular2-token/issues/445

**Comment by arjenbrandenburgh** [comment]
@neroniaky and I are currently working on a version with HttpClient support and HttpInterceptors. Give us a few more days before we can release an alpha.

**Comment by colmben** [comment]
I have a working version on my fork if you want to have a look.

**Comment by colmben** [comment]
Branch feature/httpClient

**Comment by arjenbrandenburgh** [comment]
Initial version is now in branch 6.x
