### ISSUE TITLE
Does this package support github oauth?

### ISSUE THREAD

**Issue by gbrl** [neroniaky/angular2-token#32]
I don't see anything in the docs about oauth, but I do see some configuration for OAuth with Github in the file angular2-token.service.ts:125
:D 
Is OAuth support a work in progress?

**Comment by neroniaky** [comment]
@gbrl exactly 😉. I had some problems with Angular2 RC6, didn't get around to try it with final yet.

**Comment by gbrl** [comment]
OK!
