### ISSUE TITLE
Getting validateTokenPath of 'undefined'?

### ISSUE THREAD

**Issue by AlexanderKozhevin** [neroniaky/angular2-token#329]
I tried to initialize  it inside my service. 
But keep getting this error. What is it related to?

Initialization inside components works perfect.

**Comment by tomfloresa** [comment]
It seems that your sevice is unable to acces the authToken config. Try to add in your service's constructor the validateTokenPath property.

``
      this._auth.init({
        validateTokenPath: 'PATH-TO-VALIDATION'
      });
``
