### ISSUE TITLE
Please update to support angular5

### ISSUE THREAD

**Issue by raysuelzer** [neroniaky/angular2-token#375]
The package works fine with angular5, but shows peer dependency issues.

![image](https://user-images.githubusercontent.com/1176341/32922621-e7ef17ca-cae7-11e7-8dde-9d7de79bc3f6.png)

**Comment by neroniaky** [comment]
Hey @raysuelzer, just published 0.2.0-beta.13 which works with Angular 5.0. Sorry for the delay.
