### ISSUE TITLE
currentUser doesn't seem to work

### ISSUE THREAD

**Issue by jasonswett** [neroniaky/angular2-token#39]
When I try to use `_tokenService.currentUser`, I get:

`Property 'currentUser' does not exist on type 'Angular2TokenService'.`

Any ideas?

**Comment by neroniaky** [comment]
Hey @jasonswett, thanks for your issue. The README was wrong, please use `.currentUserType`.

**Comment by jasonswett** [comment]
Thanks, although `currentUserType` seems to be null. Using `currentUserData` seems to work.
