### ISSUE TITLE
How initialize for use Bearer token?

### ISSUE THREAD

**Issue by DudeFactory** [neroniaky/angular2-token#4]
How initialize for use Bearer token?
I don't understand how use it.

**Comment by neroniaky** [comment]
@DudeFactory if you use `Angular2-Token` with the `devise token auth` gem, bearer token authentication is enabled by default. So just follow the guide to install `devise token auth` [here](https://github.com/lynndylanhurley/devise_token_auth#installation) and then install `Angular2-Token` an described in the readme.

Hope I got your question right and thank you for your feedback!

**Comment by neroniaky** [comment]
Im closing this issue because no response in 7 days. If you have any further questions please send them via Gitter.
