### ISSUE TITLE
Persisting user sessions

### ISSUE THREAD

**Issue by jasonswett** [neroniaky/angular2-token#40]
I'm writing a somewhat in-depth tutorial on Angular2-Token with devise_token_auth for my book Angular for Rails Developers.

I'm kind of stuck on a certain step. After I use Angular2-Token to sign in, if I refresh the page, `_tokenService.currentUserData` is no longer present.

How do I get the user to stay logged in?

**Comment by jasonswett** [comment]
Okay, I've found that if I do this

```typescript
    console.log(this._tokenService.currentUserData);

    this._tokenService.validateToken().subscribe(res => {
      console.log(this._tokenService.currentUserData);
    });
```

then the first `console.log` shows `undefined` and the second one shows my user as I would expect.

It doesn't seem like I should have to do this manually, no?

**Comment by neroniaky** [comment]
Hey @jasonswett, the service staves only certain information in the local storage, which persists during page reload:
- `AuthData` (e.g. Access-Token) to set the headers for the next request
- `UserType` (e.g. ADMIN) to know where to send those information to
The first thing that the service does after a reload (if AuthData are found in the local storage) is to call `.validateToken()`, which on one hand verifies the saved token information with the backend and sets `currentUserData`.

Let me know if that helps 😃 .

**Comment by neroniaky** [comment]
Gonna close this issue for now. If you have any other questions/remarks you can use the gitter chat.

**Comment by Gauravshah** [comment]
@neroniaky is there a way to force localStorage of `currentUserData` ? I do not see a reason not to store it. The UI looks flaky when it shows logged out first, then in a second it shows "Gaurav".
Showing logged-in validating token and logging-out user still looks ok
But showing logged-out , validating and then logging-in suddenly looks strange
