### ISSUE TITLE
Do you need maintainers?

### ISSUE THREAD

**Issue by raysuelzer** [neroniaky/angular2-token#421]
It would be nice to keep this package up to date with the latest version of angular. I am willing to help maintain this package.

**Comment by neroniaky** [comment]
Hey @raysuelzer thanks for your offer. I hope I can get some work done in the next seven days, if not we should talk 😃.

**Comment by arjenbrandenburgh** [comment]
Also willing to help with maintaining this project.

**Comment by raysuelzer** [comment]
Specifically, would be great to move to rxjs6 so that we don't need to have the compat package installed for it to work.

**Comment by neroniaky** [comment]
@raysuelzer, @arjenbrandenburgh gonna add you as collaborator. Thanks!

**Comment by arjenbrandenburgh** [comment]
Is there somewhere we can discuss internally?

**Comment by neroniaky** [comment]
I was thinking either Discord or Gitter, not familiar with Slack. Do you have a suggestion?

**Comment by arjenbrandenburgh** [comment]
My preference is Slack, since I already have that running anyway most of the time.
But can also make a habit of opening Discord more often.

**Comment by neroniaky** [comment]
Just created a Slack Workspace - [Invitation Link](https://join.slack.com/t/angulartoken/shared_invite/enQtMzcwNzQyNjUxNzE0LWNjMWU1ZWE5MmJiMTQ2MTQwMjM5ZWM5OWIzNDAwNjAyNjdhN2Q2ZTQ4MWY1YjQyMjdmNDU2MzVkZTQyYzAyNjg). Feel free to join.

**Comment by neroniaky** [comment]
@raysuelzer you want to to join as well?

**Comment by arjenbrandenburgh** [comment]
@raysuelzer, can you join us on Slack?
