### ISSUE TITLE
How to implement role authorization

### ISSUE THREAD

**Issue by betosalvador** [neroniaky/angular2-token#435]
Hello, everyone.

First of all, thanks so much for this amazing plugin.

I have one Users table in my api, but each user has one role.

There is any way to keep this role in the browser session (front-end)?

I need this to show or hide some elements on the page (like an authorization).

Or there is a better way to do this (authorization for elements on page and routes)?

Thanks in advance!

**Comment by betosalvador** [comment]
There is a correct way to implement authorizations with angular2-token?

**Comment by raysuelzer** [comment]
You should be able to get this data like this...

```constructor(private tokenService: Angular2TokenService, private router: Router) {
        console.log(this.tokenService.currentUserData);  
    }```

**Comment by raysuelzer** [comment]
I use a structural directive like  <div *ifInRole=" 'Admin' " > ... </div>

**Comment by betosalvador** [comment]
Hello @raysuelzer 

sorry for my late response

Thank you very much for suggestion

**Comment by neroniaky** [comment]
Please reopen if you have any questions left.

**Comment by arjenbrandenburgh** [comment]
To complete this answer, my current implementation of an *ifInRole directive is as follows:
```js
import { Directive, Input, OnInit, TemplateRef, ViewContainerRef } from '@angular/core';
import { Angular2TokenService } from 'angular2-token';

@Directive({
    selector: '[ifInRole]'
})
export class IfInRoleDirective implements OnInit {
    @Input('ifInRole') role: string;

    constructor(private viewContainer: ViewContainerRef,
                private templateRef: TemplateRef<any>,
                private tokenService: Angular2TokenService) {
    }

    ngOnInit(): void {
        const userRole = (this.tokenService.currentUserData) ? this.tokenService.currentUserData['role'] : '';

        if (this.role === userRole) {
            this.viewContainer.createEmbeddedView(this.templateRef);
        } else {
            this.viewContainer.clear();
        }
    }
}
```
