### ISSUE TITLE
npm WARN angular2-token@0.2.0-beta.14 requires a peer of @angular/common@^5.0.0 but none is installed. You must install peer dependencies yourself.

### ISSUE THREAD

**Issue by acegilz** [neroniaky/angular2-token#441]
I am trying to update to angular 6, I think the package angular2-token is updated, however, this error keeps popping up:

`npm WARN angular2-token@0.2.0-beta.14 requires a peer of @angular/common@^5.0.0 but none is installed. You must install peer dependencies yourself.`

I see the last change on this repo was precisely update dependencies:

"@angular ...... ": ">=5", from
"@angular ....": ^5.0.0

however, the error of the old version dependency persists. (this is happening also with other packages  so i may be making some mistake updating packages)

**Comment by neroniaky** [comment]
Thanks for reporting. Should be fixed with version 0.2.0 now.
