### ISSUE TITLE
angular-token@6.0.0 checks wrong configuration variable

### ISSUE THREAD

**Issue by NiekPas** [neroniaky/angular2-token#454]
I'm implementing `angular-token@6.0.0-rc.0` and keep getting `401 Unauthorized` reponses. After some digging, I found out the auth headers are never sent along with a request. After more digging, I found out this happened because [the following block](https://github.com/neroniaky/angular2-token/blob/6.x/projects/angular-token/src/lib/angular-token.interceptor.ts#L24) is never reached:

    // Add the headers if the request is going to the configured server
        if (this.tokenService.currentAuthData && req.url.match(this.tokenService.apiPath)) {
            (/** @type {?} */ (Object)).assign(baseHeaders, {
                'access-token': this.tokenService.currentAuthData.accessToken,
                'client': this.tokenService.currentAuthData.client,
                'expiry': this.tokenService.currentAuthData.expiry,
                'token-type': this.tokenService.currentAuthData.tokenType,
                'uid': this.tokenService.currentAuthData.uid
            });
        }

`req.url.match(this.tokenService.apiPath)` evaluates to `false` because I don't have `apiPath` configured, since I have several resources I want to modify.

Correct me if I'm wrong, but to my knowledge, `req.url.match(this.tokenService.apiPath)` should be replaced with `req.url.match(this.tokenService.apiBase)`, since we want to check whether the request is going to the configured **server**, not to the configured `apiPath`. I'll open a PR if necessary.

**Comment by arjenbrandenburgh** [comment]
You can open a PR for this. Haven't checked yet, but seems you're right.

**Comment by neroniaky** [comment]
Thanks!
