### ISSUE TITLE
Property 'queryParams' does not exist on type 'RouterState'.

### ISSUE THREAD

**Issue by raymondmuller** [neroniaky/angular2-token#5]
Getting this error: (Angular2 RC5)
```
/node_modules/angular2-token/src/angular2-token.service.ts:288:38 
    Property 'queryParams' does not exist on type 'RouterState'.
```

**Comment by neroniaky** [comment]
@raymondmuller Usually this error comes up when you don't have any routes defined. Could that be the case? 
`Angular2-Token` tries to read from the router to check if a token is passed via the url params. Gonna try to publish a fix today. Otherwise you can just add empty routing to your main module, which should fix it.

**Comment by raymondmuller** [comment]
@neroniaky Thanks for the quick response. I do have routes defined, which I import in app.module.ts. I've used the following boilerplate (Angular2-webpack-starter from AngularClass)
My app module looks similar to this (https://github.com/AngularClass/angular2-webpack-starter/blob/master/src/app/app.module.ts).

**Comment by neroniaky** [comment]
@raymondmuller maybe this has something to do with their experimental HMR. Not sure, need to look into it. Should be a small fix anyways, gonna try to upload it as soon as possible.
You can take a look [here](https://github.com/neroniaky/angular2-token-example) for a working example.

**Comment by raymondmuller** [comment]
@neroniaky Thanks, appreciate it :)

**Comment by neroniaky** [comment]
@raymondmuller `angular2-webpack-starter` recently changed the `@angular/router` package from the official "3.0.0-rc.1" to a custom build. I just publish version 0.1.3, which should fix the problem. Could you give it a try?

**Comment by raymondmuller** [comment]
@neroniaky Seems to work fine. Thanks for the quick fix!
