### ISSUE TITLE
Callback after token validate error

### ISSUE THREAD

**Issue by YuriGitHub** [neroniaky/angular2-token#55]
Hi guys. Can you create callback path after token validate error.
For example: User was deleted by admin and i have just error 401 (Unauthorized)

**Comment by neroniaky** [comment]
@YuriGitHub thanks for your suggestion. Gonna take a look into it.

**Comment by cybey** [comment]
When my validate call fails and receive a "Unauthorized" message, the service still indicates that the user is logged in.

Going to assume that the issue I'm having with that is related to this one.

**Comment by neroniaky** [comment]
@YuriGitHub @cybey right now only `.signOut()` reset all data and deletes the local storage. If you want it to work as you described you have to call `.signOut()` yourself on a failed validate. This is probably something that should be implemented (and an option to turn it off). PR anyone? 😃

**Comment by cybey** [comment]
See #64
