### ISSUE TITLE
http://localhost:3001/angular2-token 404 Not Found 

### ISSUE THREAD

**Issue by kamrantgp** [neroniaky/angular2-token#57]
Hi,

I installed angular2-token based as the installation guide, somehow I get this error on the console.

I can see that the package is installed under node_modules. 

I would very much appreciate any help or guidance you are able to give me. 

FIXED: by adding 
      'angular2-token' :'npm:angular2-token/src/angular2-token.service.js', 
to "systemjs.config.js"

**Comment by neroniaky** [comment]
@kamrantgp so the issue can be closed?

**Comment by bpeterson1663** [comment]
Hey so I ran into this issue as well and I added the line that kamrantgp said to add
` 'angular2-token' :'npm:angular2-token/src/angular2-token.service.js',`
to my systemjs.config.js; however, now I am getting an `/traceur (404) Not Found` error

<img width="1264" alt="screen shot 2017-04-17 at 11 23 28 pm" src="https://cloud.githubusercontent.com/assets/15317676/25114609/6a90f2b8-23c5-11e7-8a17-2e1a95a16ebd.png">

Any help would be greatly appreciated! @neroniaky Not sure if you want me to start a new issue on this or if I am missing something simple! (which is most likely the case) :)

**Comment by Anyoks** [comment]
I am using `angular-token` in the front end with:

```
Angular CLI: 6.0.8
Node: 11.10.0
OS: linux x64
Angular: 6.1.7
typescript 2.7.2
webpack 4.8.3
```
I have a `rails 5` back-end configures with `cors.`
I get a Still get this error when I attempt logging in:
`Object { body: {…}, url: "http://localhost:3000/auth/sign_in", headers: {…}, status: 404, statusText: "Not Found" }`

Here's the sign in code:

```
this.tokenService.signIn({
      login:    this.email.value,
      password: this.password.value
  }).subscribe(
      res =>      console.log(res),
      // UsersModule.first_name
      error =>    console.log(error)
  );
```
I have tried, changing proxy settings in `proxy.conf.json` but nothing. 

Any assistance will be highly appreciated.
