### ISSUE TITLE
angular2-token beta 0.2.0 error

### ISSUE THREAD

**Issue by alexdzh** [neroniaky/angular2-token#58]
After 0.2.0 version installation error message 
a2t-ui.forms.ts:8 Uncaught TypeError: __WEBPACK_IMPORTED_MODULE_1____.f is not a constructor(…)
is appear.

**Comment by percipio** [comment]
Also getting this error.

**Comment by neroniaky** [comment]
@alexdzh @percipio thanks for your issue report. Could you give me some information about your setup, because I haven not seen this error yet?

**Comment by alexdzh** [comment]
node v6.7.0
npm v3.10.3
angular-cli 1.0.0-beta.19-3
@angular/--- 2.1.2
@angular/router 3.1.2

Steps:
ng new project
      app works!

npm install angular2-token

Added to app.module.ts: 
import { Angular2TokenService } from 'angular2-token';
providers: [Angular2TokenService],

Added to app.component.ts
constructor(private _tokenService: Angular2TokenService) {
    this._tokenService.init();
  }

RESULT
a2t-ui.forms.ts:8 Uncaught TypeError: __WEBPACK_IMPORTED_MODULE_1____.f is not a constructor(…)(anonymous function) @ a2t-ui.forms.ts:8
__webpack_require__ @ bootstrap 36077d2…:52
(anonymous function) @ main.bundle.js:64759
__webpack_require__ @ bootstrap 36077d2…:52
(anonymous function) @ a2t-form.service.ts:46
__webpack_require__ @ bootstrap 36077d2…:52
(anonymous function) @ angular2-token.js:6
__webpack_require__ @ bootstrap 36077d2…:52
(anonymous function) @ main.bundle.js:40909
__webpack_require__ @ bootstrap 36077d2…:52
(anonymous function) @ app.module.ts:22
__webpack_require__ @ bootstrap 36077d2…:52
(anonymous function) @ zone.js:1426
__webpack_require__ @ bootstrap 36077d2…:52
(anonymous function) @ zone.js:1426
__webpack_require__ @ bootstrap 36077d2…:52
webpackJsonpCallback @ bootstrap 36077d2…:23
(anonymous function) @ main.bundle.js:1

**Comment by neroniaky** [comment]
@alexdzh I see you're using angular-cli. Had some problems with this before. Need to check what it's complaining about. You could downgrade to version 0.1.17, which should work with angular-cli.

**Comment by alexdzh** [comment]
I started from "After 0.2.0 version installation".
0.1.17 works good.
angular-cli more convenient for the time save reason.
I hope you will fix this bug

**Comment by neroniaky** [comment]
It should work now. Be sure to insert some kind of routing, like:

```
const appRoutes: Routes = [
  { path: 'app', component: AppComponent }
];

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule,
    RouterModule.forRoot(appRoutes)
  ],
  providers: [Angular2TokenService],
  bootstrap: [AppComponent]
})
export class AppModule { }
```
