### ISSUE TITLE
Angular CLI Implementation.

### ISSUE THREAD

**Issue by bastienlemaitre** [neroniaky/angular2-token#6]
Hi !
I want to use your component but I use Angular-Cli.

My Code: 
system-config.ts
`const map: any = {
  '@angular2-material': 'vendor/@angular2-material',
  'angular2-token': 'vendor/angular2-token'
};

/** User packages configuration. */
const packages: any = {};

// put the names of any of your Material components here
const materialPkgs:string[] = [  
  'button',
  'card',
  'core',
  'checkbox',
  'grid-list',
  'icon',
  'input',
  'list',
  'menu',
  'progress-bar',
  'progress-circle',
  'radio',
  'sidenav',
  'slider',
  'slide-toggle',
  'button-toggle',
  'tabs',
  'toolbar',
  'tooltip'
];

materialPkgs.forEach((pkg) => {
  packages[`@angular2-material/${pkg}`] = {main: `${pkg}.js`};
});

packages['angular2-token'] = {
  main: 'angular2-token.js'
};`

angular-cli-build.ts:
`// Angular-CLI build configuration
// This file lists all the node_modules files that will be used in a build
// Also see https://github.com/angular/angular-cli/wiki/3rd-party-libs

/* global require, module */

var Angular2App = require('angular-cli/lib/broccoli/angular2-app');

module.exports = function(defaults) {
  return new Angular2App(defaults, {
    vendorNpmFiles: [
      'systemjs/dist/system-polyfills.js',
      'systemjs/dist/system.src.js',
      'zone.js/dist/**/*.+(js|js.map)',
      'es6-shim/es6-shim.js',
      'reflect-metadata/**/*.+(ts|js|js.map)',
      'rxjs/**/*.+(js|js.map)',
      '@angular/**/*.+(js|js.map)',
      '@angular2-material/**/*',
      'angular2-token/**/*.+(js|js.map)',
    ]
  });
};
`
The problem is system js doesn't load all files in my dist folders, so my browser can't load the content of src..
Any idea ?
Thanks.

**Comment by neroniaky** [comment]
Hi @bastienlemaitre, I didn't test it with Angular-Cli yet. Gonna need some time to look into it.

**Comment by neroniaky** [comment]
I took some time to look into angular-cli. They are currently in the process of switching from Broccoli (which you seem to be using) to webpack. Angular2-Token requires Angular2 RC.5, which only the webpack version of angular-cli supports. Instructions for upgrading can be found [here](https://github.com/angular/angular-cli/blob/master/WEBPACK_UPDATE.md).
If you use the webpack version the installation should work according to the README.

**Comment by neroniaky** [comment]
Closing because no response in 7 days.

**Comment by jasonswett** [comment]
I'm using Angular CLI 1.0.0-beta.16 and Angular2-Token seems to work fine.
