### ISSUE TITLE
a2t-ui.forms.ts:14 says Uncaught TypeError: __WEBPACK_IMPORTED_MODULE_1____.f is not a constructor

### ISSUE THREAD

**Issue by pragun16** [neroniaky/angular2-token#62]
I've followed the installation procedures from the documentation. However, right after I import Angular2TokenService into my main module, i have the aforementioned error in my browser console (both chrome and firefox). This stops the angular2 application from loading. What could be its reason?

**Comment by neroniaky** [comment]
This seems to be the same issue as #58. You can use v0.1.17 until fixed.
