### ISSUE TITLE
Token invalidates in Safari and iOS

### ISSUE THREAD

**Issue by pmurpmur** [neroniaky/angular2-token#66]
I have been developing my own implementation of an Angular2 application that works with devise token auth for Rails. Recently I have come across a bug where my token invalidates when I am using either Safari or an iOS web view. I wanted to see if this problem persists in this project and it does. To replicate simply open the demo (https://angular2-token.herokuapp.com) in Safari, login, and keep requesting to access private resource (or validate token) with an average timed pause between each request. If you wait at least 15s between a request I can almost guarantee the token will become invalidated and throw a 401.

I am wondering if anyone has seen this and whether or not the error is the fault of devise/rails, angular2, or the project itself.

**Comment by pmurpmur** [comment]
Does anyone else at least see this issue?

**Comment by neroniaky** [comment]
Hi, I tried it on macOS:

- Chrome does not have any issues
- Firefox shows 304 warning (Not Modified) - which is correct
- Safari shows the behavior you described

Gonna require some additional investigation.

**Comment by chaskas** [comment]
Same bug!! Safari iOS and Safari Sierra (10.1.1)

**Comment by chaskas** [comment]
Solved!

Just modify this line in your Rails project:

`#config/initializers/devise_token_auth.rb

#from:
config.batch_request_buffer_throttle = 5.seconds

#to:
config.batch_request_buffer_throttle = 1.day`

Or whatever you think a session will remain alive

**Comment by acegilz** [comment]
thanks!
