### ISSUE TITLE
Get request with options

### ISSUE THREAD

**Issue by sihu** [neroniaky/angular2-token#68]
The current implementation of a get request is like that: 
```ts
get(path: string): Observable<Response>
```

The implementation of the `@angular/http` class is, that you can also pass parameters and things with the get request:

```ts
get(url: string, options?: RequestOptionsArgs): Observable<Response>;
```

This could be used, if you want to add parameters as an object like this:

```ts
this.http.get('my/url/path', { search: params }
```

I would suggest to extend the get request with an optional `options`-parameter, since this class could be a simple wrapper which just decorates the standard-requests with the headers. 

maybe there is a reason why it is not done like that and before i start coding something i wanted to open the discussion. What do you think?

**Comment by sihu** [comment]
i just saw this is a duplication of #36. i fully support the input of @ezilocchi

**Comment by neroniaky** [comment]
Hey @sihu, thanks for your Input. Angular2-Token works quite similar to `@angular/http`, but maybe not similar enough. 

Both wrap a general http-method with the more the simple calls like `.get()`. So if you need to add optional parameters you can use `.sendHttpRequest()` directly. [Link](https://github.com/neroniaky/angular2-token#sendhttprequest)

But you bring up a good point, that the Angular2-Token should be as close as possible to the`@angular/http` implementation. I could see two changes:

- Add the options parameter to the simple calls (gonna be a lot of request options merging 😃 )
- Change the name of `.sendHttpRequest()` to `.request()`

**Comment by sihu** [comment]
hey @neroniaky thanks for the fast answer and suggestions. i will not find time in the next days but i  hope i can contribute soon something to the project soon! i will bring in first some architectural ideas to https://github.com/neroniaky/angular2-token/issues/36
