### ISSUE TITLE
Error when compiling with rootDir option

### ISSUE THREAD

**Issue by micdahl** [neroniaky/angular2-token#69]
When compiling with rootDir option, the module does not compile.
Error message is:
`error TS6059: File '/tsc/node_modules/angular2-token/src/a2t-ui/a2t-reset-password/a2t-reset-password.component.ts' is not under 'rootDir' '/tsc/script'. 'rootDir' is expected to contain all source files.`

My package.json:
```
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false,
    "rootDir": "script",
    "outDir": "webroot/script",
    "watch": true
  },
  "exclude": [
    "node_modules",
    "typings"
  ]
}
```

After some research, I ended up here: https://github.com/valor-software/ng2-select/issues/161.
There seems to be some problem with containing .ts-Files?

**Comment by neroniaky** [comment]
The npm package used to have only .ts-Files. I switched it to compiled .js-Files because of angular-cli using broccoli as bundler, which couldn't handle them. I don't know if going all compiled is the right way or even possible.

**Comment by micdahl** [comment]
Unfortunately, I am not able to contribute anything to answer this questions at the moment, as I have just started learning TypeScript and Angular2.

**Comment by neroniaky** [comment]
@micdahl could you give it another try? Should be fixed with 0.2.0-beta.7. Thanks!

**Comment by micdahl** [comment]
@neroniaky Unfortunately I am very busy at the moment. Will try as soon as I can spare some time. Many thanks for your work!

**Comment by neroniaky** [comment]
@micdahl I gonna close this for now, because the compilation has changed quite a bit. You can reopen this bug when you got a chance to try it out. Thanks!
