### ISSUE TITLE
Saving access-token and other credentials 

### ISSUE THREAD

**Issue by pragun16** [neroniaky/angular2-token#70]
how do we save the access-token sent in a response header from a backend server so that the access token together with other credentials can be used later to consume the api? i looked into  this._tokenService.init(globalOptions:{}) but then i needed to store the token after the service is initialized. How can we do it?

**Comment by neroniaky** [comment]
If you use the devise token auth gem, all the access-token/auth data handling is done by Angular2-Token. If you use custom headers you have to store/handle them yourself (e.g. in the session storage) to persist.
Hope this helps 😃 !

**Comment by pragun16** [comment]
i'm using devise_token_auth obviously. seems like i'm understanding things a bit now. thanks anyways :)
