### ISSUE TITLE
Session Service: Error Fetching Response

### ISSUE THREAD

**Issue by pragun16** [neroniaky/angular2-token#72]
So I've been using this package together with devise_token_auth and when initially i try to login with unauthorized credentials, it throws this error in the console. Is there any way to suppress it or in any ways can i deal with it? I've not understood the behavior of this error.

**Comment by neroniaky** [comment]
Hey, the error gets thrown if the backend responds with an error, which could be wrong credentials, as well as others (e.g. no connection). I guess the wording is a little misleading.

**Comment by pragun16** [comment]
well that's totally fine but then i donot want that console.log to happen from the library. seems unusual. also, i get a post or get or delete request error with the request/response parameters before that console.log happens.
