### ISSUE TITLE
Issue getting a2t-ui folder

### ISSUE THREAD

**Issue by pjq100** [neroniaky/angular2-token#73]
I'm having an issue configuring system.js to correctly find and include the a2t-ui module.  It isn't having any problem with the angular2-token.js file or any of the files it requires other than the a2t-ui ones.  Here's the errors I'm getting:

Navigated to http://localhost:3000/
GET http://localhost:3000/node_modules/angular2-token/src/a2t-ui/ 404 (Not Found)
Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:3000/node_modules/angular2-token/src/a2t-ui/(…)
GET http://localhost:3000/node_modules/angular2-token/src/a2t-ui/a2t-shared.js 404 (Not Found)
GET http://localhost:3000/node_modules/angular2-token/src/a2t-ui/ 404 (Not Found

And here's my system.js file:

[systemjs.config.txt](https://github.com/neroniaky/angular2-token/files/617613/systemjs.config.txt)

`(function (global) {
  System.config({
    paths: {
      // paths serve as alias
      'npm:': 'node_modules/'
    },
    // map tells the System loader where to look for things
    map: {
      // our app is within the app folder
      app: 'app/client/',
      // angular bundles
      '@angular/core': 'npm:@angular/core/bundles/core.umd.js',
      '@angular/common': 'npm:@angular/common/bundles/common.umd.js',
      '@angular/compiler': 'npm:@angular/compiler/bundles/compiler.umd.js',
      '@angular/platform-browser': 'npm:@angular/platform-browser/bundles/platform-browser.umd.js',
      '@angular/platform-browser-dynamic': 'npm:@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js',
      '@angular/http': 'npm:@angular/http/bundles/http.umd.js',
      '@angular/router': 'npm:@angular/router/bundles/router.umd.js',
      '@angular/forms': 'npm:@angular/forms/bundles/forms.umd.js',
      '@angular/upgrade': 'npm:@angular/upgrade/bundles/upgrade.umd.js',
      // other libraries
      'rxjs':                      'npm:rxjs',
      'angular-in-memory-web-api': 'npm:angular-in-memory-web-api/bundles/in-memory-web-api.umd.js',
      'angular2-token': 'npm:angular2-token',
    },
    // packages tells the System loader how to load when no filename and/or no extension
    packages: {
      app: {
        main: './main.js',
        defaultExtension: 'js'
      },
      rxjs: {
        defaultExtension: 'js'
      },
      'angular2-token': {
        main: './angular2-token.js', defaultExtension: 'js'
      }
    }
  });
})(this);

**Comment by Tybot204** [comment]
@pjq100 try updating to the latest version of angular2-token and see if that fixes your issue. I was having a similar issue related to the a2t-ui folder that was resolved in `v0.2.0-beta.5`.
