### ISSUE TITLE
EXCEPTION: result is undefined

### ISSUE THREAD

**Issue by pragun16** [neroniaky/angular2-token#74]
I've been getting this issue while i try to re-register a user. i.e. email id already used. I'm using devise_token_auth with angular2-token.
![angular2-token](https://cloud.githubusercontent.com/assets/16092672/20697674/2f444cd8-b623-11e6-9db8-53dafba1b631.jpg)

**Comment by pragun16** [comment]
I somehow managed to suppress the error by adding an exception handler. However, it'd be great if there were any better ways to deal with the issue. The browser's console is filled with logs generated by the angular2-token library.

**Comment by neroniaky** [comment]
@pragun16 suggestions? PR are always welcome 😉 .
