### ISSUE TITLE
Sending additional sign up parameters to devise

### ISSUE THREAD

**Issue by pragun16** [neroniaky/angular2-token#88]
How can I send additional sign up parameters like name, age etc. to devise using registerAccount() ? Can it be customized for sending additional parameters or do I have to use the http post method separately?

**Comment by neroniaky** [comment]
Angular2-Token does not support additional parameters with the `registerAccount()` method currently. You could use post, but it requires some configuration on the Devise side too.

**Comment by pragun16** [comment]
Thanks :) I'm pretty aware about the configuration in Devise as well. I shall use http post for the time being.
