### ISSUE TITLE
currentUserData not available after refresh

### ISSUE THREAD

**Issue by cybey** [neroniaky/angular2-token#91]
Not sure whether there's an easy way to fix this, but here it goes. I have a user system that has all users in a single table, but they still can have specific roles. Like "admin" or "regular". Since I simply have this as a field in the database, I cannot use the built in Multiple User Types. I can however just let the backend return this field to the frontend.

So when I have a page guarded by canActivate, I could have something like this:
```javascript
canActivate() {
    return this._tokenService && this._tokenService.currentUserData && this._tokenService.currentUserData['role'] === 'admin';
}
```
and call this in the routing.

Now here's the problem. When you sign in and click to the guarded page, it works fine. However, when you directly go to the guarded page's URL (or refresh), the canActivate checks the currentUserData before the validate_token succeeds. So when canActivate() is called, currentUserData is undefined.

**Steps to reproduce:**
1. Sign in
2. Go to authorized canActivate page using code above
3. Refresh

Any idea on if or how to properly solve this?

**Comment by neroniaky** [comment]
A quick fix would be to subscribe to `.validateToken()`. It returns an observable, so you can be sure that currentUserData is set.

**Comment by Gauravshah** [comment]
the UI looks flaky , it shows UI for logged out first and then shows up for logged in. Anything to sort out that ?
